import streamlit as st
import re, os
import pandas as pd
import math
import plotly.graph_objects as go

# הגדרות דף - Darwish CNC Pro 41.4
st.set_page_config(page_title="Darwish CNC Pro 41.4 - Multi-Pass & Full Logic", layout="wide")

# אתחול פרופיל אבי המלא (T1-T49) - שימור 100% מגרסה 41.3
if 'profiles' not in st.session_state:
    st.session_state.profiles = {
        "אבי": {
            "tools": [
                {"T_CNC": "T1", "קוטר": 40.0, "תיאור": "כרסום 40 (ניקוי פוקט)", "צבע": "brown"},
                {"T_CNC": "T2", "קוטר": 6.0, "תיאור": "כרסום 6 (קונטור חיצוני)", "צבע": "red"},
                {"T_CNC": "T3", "קוטר": 8.0, "תיאור": "כרסום 8", "צבע": "green"},
                {"T_CNC": "T4", "קוטר": 12.0, "תיאור": "כרסום 12", "צבע": "purple"},
                {"T_CNC": "T8", "קוטר": 19.0, "תיאור": "כרסום 19/20", "צבע": "darkblue"},
                {"T_CNC": "T11", "קוטר": 3.0, "תיאור": "כרסום 3", "צבע": "pink"},
                {"T_CNC": "T13", "קוטר": 0.2, "תיאור": "כרסום 90/45 (גירונג)", "צבע": "gold"},
                {"T_CNC": "T15", "קוטר": 5.0, "תיאור": "כרסום 5", "צבע": "lightgreen"},
                {"T_CNC": "T48", "קוטר": 3.0, "תיאור": "מקדח 3", "צבע": "gray"},
                {"T_CNC": "T45", "קוטר": 5.0, "תיאור": "מקדח 5 (עובר)", "צבע": "white"},
                {"T_CNC": "T44", "קוטר": 5.0, "תיאור": "מקדח 5 (רגיל)", "צבע": "gray"},
                {"T_CNC": "T42", "קוטר": 5.0, "תיאור": "מקדח 5 (שלישייה)", "צבע": "lightgray"},
                {"T_CNC": "T47", "קוטר": 8.0, "תיאור": "מקדח 8", "צבע": "darkgreen"},
                {"T_CNC": "T46", "קוטר": 10.0, "תיאור": "מקדח 10", "צבע": "blue"},
                {"T_CNC": "T49", "קוטר": 15.0, "תיאור": "מקדח 15 (קבינאו)", "צבע": "yellow"},
                {"T_CNC": "T6", "קוטר": 35.0, "תיאור": "מקדח 35 (צירים)", "צבע": "orange"}
            ],
            "bed_x": 1300, "bed_y": 3050
        }
    }

# פונקציות עזר (שימור מגרסה 41.3)
def get_dist(p1, p2):
    return math.sqrt((p1['x'] - p2['x'])**2 + (p1['y'] - p2['y'])**2)

def optimize_path(points):
    if not points: return []
    optimized = []
    current_pos = {'x': 0, 'y': 0}
    remaining = points[:]
    while remaining:
        next_pt = min(remaining, key=lambda p: get_dist(current_pos, p))
        optimized.append(next_pt)
        remaining.remove(next_pt)
        current_pos = next_pt
    return optimized

def get_safe_float(key, block, default=0.0):
    match = re.search(f'{key}="([^"]*)"', block)
    if not match: return default
    try: return float(match.group(1))
    except:
        nums = re.findall(r'[\d.-]+', match.group(1))
        return float(nums[0]) if nums else default

# לוגיקת המרה משופרת 41.4 (כולל Multi-Pass)
def convert_logic(mpr_text, rotate_90, zero_nesting, global_z_off, tool_map, local_offsets, custom_order, step_downs):
    thickness = get_safe_float('t', mpr_text, 16.0)
    raw_drills = []
    geos = {}
    nc = ["%", f"(NC GENERATED BY DARWISH PRO 41.40 - MULTI-PASS)", "G90 G54 G21"]
    
    # חילוץ גיאומטריות (שימור 41.3)
    parts = re.split(r'\](\d+)', mpr_text)
    for i in range(1, len(parts), 2):
        if parts[i] == "1": continue 
        pts = []
        for elem in re.split(r'\$E\d+', parts[i+1]):
            x_m = re.search(r'X=([\d.-]+)', elem)
            y_m = re.search(r'Y=([\d.-]+)', elem)
            if x_m and y_m: pts.append([float(x_m.group(1)), float(y_m.group(1))])
        if pts: geos[parts[i]] = pts

    # עיבוד קידוחים (שוחזר מ-41.3)
    for m in re.finditer(r'<102(.*?)(?=<|\!|\[H)', mpr_text, re.DOTALL):
        b = m.group(1)
        xa, ya, ti = [get_safe_float(k, b) for k in ['XA', 'YA', 'TI']]
        t_mpr_search = re.search(r'DU="([^"]*)"', b)
        t_mpr = t_mpr_search.group(1) if t_mpr_search else "5"
        t_cnc = tool_map.get(t_mpr, "T44")
        l_off = local_offsets.get(t_mpr, 0.0)
        f_z = (thickness - ti) + global_z_off + l_off
        raw_drills.append({'x': xa, 'y': ya, 'z': f_z, 't': t_cnc, 'dia': float(t_mpr) if t_mpr.replace('.','').isdigit() else 5.0, 'l_off': l_off})

    # עיבוד כרסומים (כולל יצירת Unique ID לפסיעות)
    milling_ops = []
    op_counter_id = 1
    for m in re.finditer(r'<(105|130)(.*?)(?=<|\!|\[H)', mpr_text, re.DOTALL):
        bc = m.group(2)
        tno = re.search(r'TNO="([^"]*)"', bc).group(1) if re.search(r'TNO="([^"]*)"', bc) else "142"
        l_off = local_offsets.get(tno, 0.0)
        za = get_safe_float('ZA', bc) + global_z_off + l_off
        ea = re.search(r'EA="(\d+):', bc)
        geo_id = ea.group(1) if ea else None
        
        if geo_id in geos:
            op_uid = f"{tno}_{op_counter_id}"
            milling_ops.append({
                'uid': op_uid, 'geo_id': geo_id, 'tno': tno, 'z': za, 
                'l_off': l_off, 'pts': [p[:] for p in geos[geo_id]]
            })
            op_counter_id += 1

    # טרנספורמציות (שוחזר מ-41.3)
    if rotate_90:
        for d in raw_drills: d['x'], d['y'] = -d['y'], d['x']
        for op in milling_ops:
            for p in op['pts']: p[0], p[1] = -p[1], p[0]

    all_x = [d['x'] for d in raw_drills] + [p[0] for op in milling_ops for p in op['pts']]
    all_y = [d['y'] for d in raw_drills] + [p[1] for op in milling_ops for p in op['pts']]
    mx, my = (min(all_x), min(all_y)) if zero_nesting and all_x else (0,0)
    
    for d in raw_drills: d['x'] -= mx; d['y'] -= my
    for op in milling_ops:
        for p in op['pts']: p[0] -= mx; p[1] -= my

    # יצירת קוד NC ו-Timeline (משולב Multi-Pass)
    timeline = []
    op_counter = 1

    # קידוחים (שימור לוגיקה)
    drills_by_tool = {}
    for d in raw_drills: drills_by_tool.setdefault(d['t'], []).append(d)
    for t_id in sorted(drills_by_tool.keys()):
        opts = optimize_path(drills_by_tool[t_id])
        nc.append(f"M6 {t_id} (OP {op_counter})")
        timeline.append({"op": op_counter, "tool": t_id, "type": "Drill"})
        for d in opts:
            d['op_idx'] = op_counter
            nc.extend([f"G0 X{d['x']:.3f} Y{d['y']:.3f}", f"G1 Z{d['z']:.3f} F1000", f"G0 Z{thickness+20}"])
        op_counter += 1

    # כרסומים (Multi-Pass Logic)
    milling_by_tool = {}
    for op in milling_ops:
        t_cnc = tool_map.get(op['tno'], "T2")
        milling_by_tool.setdefault(t_cnc, []).append(op)
    
    final_order = [t for t in custom_order if t in milling_by_tool and t != "T2"]
    final_order += [t for t in sorted(milling_by_tool.keys()) if t not in final_order and t != "T2"]
    if "T2" in milling_by_tool: final_order.append("T2")

    for t_id in final_order:
        nc.append(f"M6 {t_id} (OP {op_counter})")
        timeline.append({"op": op_counter, "tool": t_id, "type": "Mill"})
        for op in milling_by_tool[t_id]:
            op['op_idx'] = op_counter
            pts = op['pts']
            step = step_downs.get(op['uid'], 0.0)
            target_z = op['z']
            
            # חישוב שכבות
            layers = []
            if step > 0 and target_z < thickness:
                curr_z = thickness - step
                while curr_z > target_z:
                    layers.append(curr_z)
                    curr_z -= step
            layers.append(target_z)

            for l_idx, z_depth in enumerate(layers):
                nc.append(f"(PASS {l_idx+1} Z={z_depth:.2f})")
                nc.append(f"G0 X{pts[0][0]:.3f} Y{pts[0][1]:.3f}")
                nc.append(f"G1 Z{z_depth:.3f} F2000")
                for p in pts[1:]: nc.append(f"G1 X{p[0]:.3f} Y{p[1]:.3f} F3000")
                nc.append(f"G0 Z{thickness+20}")
        op_counter += 1

    nc.append("M30\n%")
    return "\n".join(nc), raw_drills, milling_ops, thickness, timeline

# הדמיה (שימור ScrollZoom ו-Hover מ-41.3)
def plot_2d_pro(drills, milling_ops, thickness, cfg, tool_map):
    fig = go.Figure()
    fig.add_shape(type="rect", x0=0, y0=0, x1=3050, y1=1300, fillcolor="whitesmoke", line=dict(color="black", width=2), layer="below")
    
    for op in milling_ops:
        target_t = tool_map.get(op['tno'], "T2")
        t_info = next((t for t in cfg['tools'] if t['T_CNC'] == target_t), {"תיאור": "כרסום", "צבע": "red"})
        x_p, y_p = zip(*op['pts'])
        fig.add_trace(go.Scatter(
            x=x_p, y=y_p, mode='lines', line=dict(color=t_info['צבע'], width=2),
            name=f"פעולה {op['op_idx']}",
            hovertemplate=f"<b>פעולה {op['op_idx']}</b><br>כלי: {op['tno']} ({t_info['תיאור']})<br>גובה מהשולחן: {op['z']:.2f}mm<br>תיקון מקומי: {op['l_off']:.2f}mm<extra></extra>"
        ))
    
    for d in drills:
        fig.add_trace(go.Scatter(
            x=[d['x']], y=[d['y']], mode='markers',
            marker=dict(size=d['dia'], sizemode='diameter', color='blue', line=dict(width=1, color='black')),
            hovertemplate=f"<b>פעולה {d['op_idx']}</b><br>כלי: {d['t']}<br>עומק סופי: {d['z']:.2f}mm<extra></extra>"
        ))

    fig.update_layout(width=900, height=500, template="plotly_white", dragmode='pan', showlegend=False)
    fig.update_yaxes(scaleanchor="x", scaleratio=1)
    st.plotly_chart(fig, use_container_width=True, config={'scrollZoom': True})

# --- UI ---
st.sidebar.title("🛠️ Darwish PRO 41.40")
cfg = st.session_state.profiles["אבי"]

nest = st.sidebar.checkbox("Nesting", value=True)
rot = st.sidebar.checkbox("סובב 90°", value=False)
gz_off = st.sidebar.slider("כיול Z גלובלי (מילימטר)", -3.0, 3.0, 0.0, 0.1)

uploaded = st.file_uploader("טען קבצי MPR", accept_multiple_files=True)
if uploaded:
    for f in uploaded:
        mpr_c = f.getvalue().decode('utf-8', errors='ignore')
        detected = sorted(list(set(re.findall(r'(?:DU|TNO)="([^"]*)"', mpr_c))))
        
        with st.sidebar.expander(f"הגדרות: {f.name}", expanded=True):
            t_map = {}; l_offsets = {}; step_downs = {}
            for t_id in detected:
                col1, col2 = st.columns([2, 1])
                auto_idx = 6 if t_id == "130" else (3 if t_id == "128" else 12 if t_id in ["8.0000", "8"] else 1)
                t_map[t_id] = col1.selectbox(f"MPR {t_id}:", [t['T_CNC'] for t in cfg['tools']], index=min(auto_idx, 15), key=f"t_{f.name}_{t_id}")
                l_offsets[t_id] = col2.number_input("Z+/-", value=0.0, step=0.1, key=f"z_{f.name}_{t_id}")
            
            # שליטה בפסיעות לפי Unique ID (רק לכרסומים)
            st.markdown("---")
            st.markdown("**שליטה בפסיעות (מילימטר):**")
            # חילוץ אופרציות לצורך ה-UI
            _, _, temp_ops, _, _ = convert_logic(mpr_c, rot, nest, gz_off, t_map, l_offsets, [], {})
            for op in temp_ops:
                step_downs[op['uid']] = st.number_input(f"פעולה {op['tno']} (ID:{op['uid']})", 0.0, 20.0, 0.0, 1.0, key=f"sd_{f.name}_{op['uid']}")

            m_tools = list(set([t_map[tid] for tid in t_map if tid.startswith('1')]))
            m_order = st.multiselect("סדר כרסומים:", m_tools, key=f"ord_{f.name}")

        nc, drls, ops, thick, tm = convert_logic(mpr_c, rot, nest, gz_off, t_map, l_offsets, m_order, step_downs)
        
        st.subheader(f"📋 סדר פעולות: {f.name}")
        tcols = st.columns(len(tm))
        for idx, step in enumerate(tm):
            tcols[idx].info(f"#{step['op']}\n{step['tool']}\n({step['type']})")
        
        plot_2d_pro(drls, ops, thick, cfg, t_map)
        st.download_button(f"📥 הורד NC: {f.name}", nc, f.name.replace(".mpr", ".nc"))
